### ISSUE TITLE
SPM Build Failure

### ISSUE THREAD

**Issue by Sherlouk** [exyte/Macaw#483]
```
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/model/scene/Text.swift:71:30: error: 'systemFont(ofSize:weight:)' is only available on OS X 10.11 or newer
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/model/scene/Text.swift:90:33: error: 'regular' is only available on OS X 10.11 or newer
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/model/scene/Text.swift:92:33: error: 'bold' is only available on OS X 10.11 or newer
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/model/scene/Text.swift:94:33: error: 'semibold' is only available on OS X 10.11 or newer
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/model/scene/Text.swift:96:33: error: 'light' is only available on OS X 10.11 or newer
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/model/scene/Text.swift:98:33: error: 'regular' is only available on OS X 10.11 or newer
/Volumes/Sherlouk/Projects/Personal/Macaw/Source/platform/macOS/Graphics_macOS.swift:96:19: error: 'noIntrinsicMetric' is only available on OS X 10.11 or newer
```

Hey,

I'm currently not able to compile the project either at the latest tag or using the latest code in `master` using `swift build` (getting the errors above). Compiles fine through Xcode.

Any ideas or something that I may be missing?

Tested on macOS 10.13.6 using Xcode 9.3 and Xcode 10.0

Thanks in advance

**Comment by amarunko** [comment]
Hi, @Sherlouk, sorry, but we drop support for SPM, you can find discussions [here](https://github.com/exyte/Macaw/issues/256). I tested to build on 10.13, works as expected. Did you try building without SPM?

**Comment by Sherlouk** [comment]
I compiled it perfectly fine through Xcode but unfortunately I wanted to use the library in the scope of my SPM project which would obviously make this a non starter

Not a problem though if that's a decision you've made - could I suggest removing the Package.swift though as this was what made me assume you had support!

Thanks again!

**Comment by amarunko** [comment]
Yea, you are right, I removed package config file.

**Comment by Sherlouk** [comment]
Sweet will close this then! Not supported, not an issue.
