### ISSUE TITLE
Carthage Build Failure

### ISSUE THREAD

**Issue by uimike** [exyte/Macaw#176]
Hello,

I'm trying to get the Macaw framework installed for iOS, and the build is failing when running 'carthage update Macaw'. The Cartfile includes: 
`github "Exyte/Macaw" ~> 0.9.0`

In the log, it seems the build may be failing due macOS-related code, specifically NSImage? Here are the relevant lines from the log:

```
/Carthage/Checkouts/Macaw/Source/model/scene/Image.swift:142:30: error: use of unresolved identifier 'NSImage'
        return MImage(named: NSImage.Name(rawValue: src))
                             ^~~~~~~
/Carthage/Checkouts/Macaw/Source/model/scene/Image.swift:45:15: note: did you mean 'mImage'?
  private var mImage: MImage?
              ^
/Carthage/Checkouts/Macaw/Source/model/scene/Image.swift:7:12: note: did you mean 'Image'?
open class Image: Node {
           ^
/Carthage/Checkouts/Macaw/Source/platform/macOS/Common_macOS.swift:19:20: note: did you mean 'MImage'?
  public typealias MImage = NSImage
                   ^
CoreGraphics.CGImage:1:14: note: did you mean 'CGImage'?
public class CGImage : _CFObject {
             ^
/Carthage/Checkouts/Macaw/Source/render/ImageRenderer.swift:66:37: error: use of unresolved identifier 'NSImage'
        let osImage = MImage(named: NSImage.Name(rawValue: image.src))
                                    ^~~~~~~
/Carthage/Checkouts/Macaw/Source/model/scene/Image.swift:7:12: note: did you mean 'Image'?
open class Image: Node {
           ^
/Carthage/Checkouts/Macaw/Source/platform/macOS/Common_macOS.swift:19:20: note: did you mean 'MImage'?
  public typealias MImage = NSImage
                   ^
CoreGraphics.CGImage:1:14: note: did you mean 'CGImage'?
public class CGImage : _CFObject {
             ^
Foundation.NSRange:1:18: note: did you mean 'NSRange'?
public typealias NSRange = _NSRange
                 ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by kayuri** [comment]
Hi @uimike! Thanks a lot for your report! We fixed this in `master` and currently work on making it into 0.9.1, will try to release ASAP.

**Comment by uimike** [comment]
Thanks for the fast response, @kayuri! I pointed the Cartfile at the master branch, and am now having a different error when running a carthage update.

Running carthage update now produces this error:

`*** Building scheme "Macaw iOS" in Macaw.xcodeproj
Failed to write to /Carthage/Build/Mac/Macaw.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Macaw.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Macaw/3b10a4735b96c7c6df6ce691b910b23868a44fa7/Build/Products/Release-iphoneos/Macaw.framework, NSFilePath=/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Macaw/3b10a4735b96c7c6df6ce691b910b23868a44fa7/Build/Products/Release-iphoneos/Macaw.framework, NSUnderlyingError=0x7fed4e5f3b00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

I am able to build successfully for simulator and device, but when I try to archive, the archive fails with errors stating it doesn't recognize classes from the Macaw framework, which I'm guessing is tied to the error above. Thanks again for your help!

**Comment by vhailor13** [comment]
Hello, @uimike !
Just fixed projects settings in master branch, you should be able to now to use it via carthage. I will add OS X target soon.

**Comment by uimike** [comment]
Thanks @vhailor13!

The carthage update command succeeds now without any issues.

However, it looks like there are still some problems when archiving my project from the Carthage build, possibly related to the architectures that Macaw is built with. Here are the relevant errors and warnings I'm getting when archiving my project:

`ld: warning: ignoring file /Documents/Project/Macaw.framework/Macaw, file was built for x86_64 which is not the architecture being linked (arm64): /Documents/Project/Macaw.framework/Macaw
ld: warning: ignoring file /Documents/Project/SWXMLHash.framework/SWXMLHash, file was built for x86_64 which is not the architecture being linked (arm64): /Documents/Project/SWXMLHash.framework/SWXMLHash
Undefined symbols for architecture arm64:
  "__T05Macaw9SVGParserCMa", referenced from:
      __T013ViewControllerC19M0_tFTf4gXn_n in ViewController.o
  "__T05Macaw7SVGViewCMa", referenced from:
      __T013ViewControllerC19M0_tFTf4gXn_n in ViewController.o
  "__T05Macaw7SVGViewCAcA4NodeC4node_SC6CGRectV5frametcfc", referenced from:
      __T013ViewControllerC19M0_tFTf4gXn_n in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

For reference, my project is archiving with the Valid Architectures of arm64, armv7, and armv7s. Again, I really appreciate the help!

**Comment by ystrot** [comment]
Can be closed now.
